INSERT INTO source_registry (
    source_code,
    source_name,
    provider_name,
    source_kind,
    base_url,
    ingestion_target,
    license_status,
    license_name,
    commercial_use_allowed,
    modification_allowed,
    attribution_required,
    refresh_cycle,
    is_active,
    notes
) VALUES
    (
        'MFDS_DRUG_GUIDE',
        '의약품개요정보(e약은요)',
        '식품의약품안전처',
        'API',
        'https://www.data.go.kr/data/15075057/openapi.do',
        'VECTOR',
        'APPROVED',
        '이용허락범위 제한 없음',
        TRUE,
        TRUE,
        TRUE,
        'REALTIME',
        TRUE,
        '효능, 사용법, 주의사항, 상호작용, 부작용, 보관법을 문단별 청크로 생성'
    ),
    (
        'MFDS_DUR',
        '의약품 병용금기 및 특정연령대 금기 정보',
        '식품의약품안전처',
        'API',
        'https://www.data.go.kr/data/15059486/openapi.do',
        'RELATIONAL',
        'APPROVED',
        '이용허락범위 제한 없음',
        TRUE,
        TRUE,
        TRUE,
        'REALTIME',
        TRUE,
        '정확한 금기 조건은 drug_safety_rule 같은 관계형 테이블에 적재'
    ),
    (
        'KDCA_HEALTH_INFO',
        '국가건강정보포털 건강정보',
        '질병관리청',
        'API',
        'https://www.data.go.kr/data/15087442/openapi.do',
        'VECTOR',
        'RESTRICTED',
        '공공누리 제4유형',
        FALSE,
        FALSE,
        TRUE,
        'REALTIME',
        FALSE,
        '상업 서비스의 임베딩·가공 사용은 별도 허가 확인 후 활성화'
    ),
    (
        'MOHW_SCREENING_RULE',
        '건강검진 검사항목별 판정기준',
        '보건복지부',
        'DOCUMENT',
        'https://law.go.kr/LSW/flDownload.do?bylClsCd=200207&flNm=%5B%EB%B3%84%EC%B2%A8+1%5D+%EA%B2%80%EC%82%AC%ED%95%AD%EB%AA%A9%EB%B3%84+%ED%8C%90%EC%A0%95%EA%B8%B0%EC%A4%80&flSeq=160922929',
        'RELATIONAL',
        'PENDING',
        NULL,
        NULL,
        NULL,
        TRUE,
        'ON_CHANGE',
        FALSE,
        '국가법령정보센터 원문 다운로드. 검사 수치는 screening_rule로 구조화하고 VDB 판정에는 사용하지 않음'
    ),
    (
        'NHIS_SCREENING_RESULT_AGG',
        '직역별 성별 연령별 건강검진 결과 집계',
        '국민건강보험공단',
        'API',
        'https://api.odcloud.kr/api/15144521/v1/uddi:281e8b27-402b-48db-85d9-d5410a73ce07',
        'RELATIONAL',
        'APPROVED',
        '이용허락범위 제한 없음',
        TRUE,
        TRUE,
        TRUE,
        'ONE_TIME',
        TRUE,
        '2022~2023 집계 180행. 개인 검사수치가 아니라 정상A/B 및 질환의심 인원 검증용'
    ),
    (
        'NHIS_SCREENING_ITEM_CODE',
        '건강검진 검사항목 코드',
        '국민건강보험공단',
        'API',
        'https://api.odcloud.kr/api/15132510/v1/uddi:14a6a890-74e1-4c8e-9e24-84961db0ad05',
        'RELATIONAL',
        'APPROVED',
        '이용허락범위 제한 없음',
        TRUE,
        TRUE,
        TRUE,
        'ONE_TIME',
        TRUE,
        '검사항목 코드·명칭·검진유형 매핑용. 판정 수치나 개인 결과는 포함하지 않음'
    ),
    (
        'NHIS_SCREENING_ITEM_BASE',
        '건강검진 검사항목 기본',
        '국민건강보험공단',
        'API',
        'https://api.odcloud.kr/api/15133104/v1/uddi:071dd3a1-89a1-4a65-b890-f4528e16ae2f',
        'RELATIONAL',
        'APPROVED',
        '이용허락범위 제한 없음',
        TRUE,
        TRUE,
        TRUE,
        'ONE_TIME',
        TRUE,
        '검사항목 코드·명칭·도메인 구분 매핑용. 판정 수치나 개인 결과는 포함하지 않음'
    ),
    (
        'NHIS_SCREENING_CLAIM_CODE',
        '건강검진 청구항목 코드',
        '국민건강보험공단',
        'API',
        'https://api.odcloud.kr/api/15132486/v1/uddi:775e4de2-f15a-4a67-84ef-9a5e50306558',
        'RELATIONAL',
        'APPROVED',
        '이용허락범위 제한 없음',
        TRUE,
        TRUE,
        TRUE,
        'ONE_TIME',
        TRUE,
        '청구 코드 매핑용. 검사 결과 해석이나 개인 검사수치 데이터가 아님'
    ),
    (
        'INTERNAL_GUIDE',
        '서비스 자체 건강관리·안전 안내',
        '서비스 운영팀',
        'INTERNAL',
        NULL,
        'VECTOR',
        'APPROVED',
        '자체 저작물',
        TRUE,
        TRUE,
        FALSE,
        'ON_CHANGE',
        TRUE,
        '의료진 검수 상태와 문서 버전을 metadata에 기록'
    )
ON CONFLICT (source_code) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    provider_name = EXCLUDED.provider_name,
    source_kind = EXCLUDED.source_kind,
    base_url = EXCLUDED.base_url,
    ingestion_target = EXCLUDED.ingestion_target,
    license_status = EXCLUDED.license_status,
    license_name = EXCLUDED.license_name,
    commercial_use_allowed = EXCLUDED.commercial_use_allowed,
    modification_allowed = EXCLUDED.modification_allowed,
    attribution_required = EXCLUDED.attribution_required,
    refresh_cycle = EXCLUDED.refresh_cycle,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes,
    updated_at = NOW();

-- 현행 2026년 고시와 전문학회 지침은 원문 추적용으로 별도 등록합니다.
-- 전문학회·KDCA 제4유형 콘텐츠는 참고 근거일 뿐 원문을 복제하거나 임베딩하지 않습니다.
INSERT INTO source_registry (
    source_code,
    source_name,
    provider_name,
    source_kind,
    base_url,
    ingestion_target,
    license_status,
    license_name,
    commercial_use_allowed,
    modification_allowed,
    attribution_required,
    refresh_cycle,
    is_active,
    notes
) VALUES
    (
        'KDA_DIABETES_GUIDELINE_2025',
        '2025 당뇨병 진료지침',
        '대한당뇨병학회',
        'PDF',
        'https://diabetes.or.kr/bbs/download.php?code=guide&number=1522',
        'REFERENCE_ONLY',
        'RESTRICTED',
        '학회 저작물',
        NULL,
        NULL,
        TRUE,
        'ON_CHANGE',
        FALSE,
        '공복혈당 설명의 근거 확인용. 원문·표를 VDB에 복제하지 않고 이용허락 또는 자체 의료진 요약 검수 필요'
    ),
    (
        'KSN_DKD_GUIDELINE_2023',
        '2023 당뇨병콩팥병 진료지침',
        '대한신장학회',
        'PDF',
        'https://www.ksn.or.kr/bbs/skin/publication/download.php?code=g_guideline&number=2159',
        'REFERENCE_ONLY',
        'RESTRICTED',
        '학회 저작물',
        NULL,
        NULL,
        TRUE,
        'ON_CHANGE',
        FALSE,
        'eGFR·알부민뇨 근거 확인용. 원문 임베딩 금지'
    ),
    (
        'KSLA_DYSLIPIDEMIA_GUIDELINE_5',
        '이상지질혈증 진료지침 제5판',
        '한국지질·동맥경화학회',
        'PDF',
        'https://www.lipid.or.kr/reference/guideline.php',
        'REFERENCE_ONLY',
        'RESTRICTED',
        '학회 저작물',
        NULL,
        NULL,
        TRUE,
        'ON_CHANGE',
        FALSE,
        '지질검사 의미와 위험도별 해석의 근거 확인용. 원문 임베딩 금지'
    ),
    (
        'KASL_HBV_GUIDELINE_2026',
        '2026 만성 B형간염 진료 가이드라인',
        '대한간학회',
        'PDF',
        'https://www.kasl.org/bbs/skin/guide/pdf_inline.php?code=guide&number=17947',
        'REFERENCE_ONLY',
        'RESTRICTED',
        '학회 저작물',
        NULL,
        NULL,
        TRUE,
        'ON_CHANGE',
        FALSE,
        'AST·ALT·GGT 설명의 근거 확인용. 원문 임베딩 금지'
    ),
    (
        'NHIS_SCREENING_GUIDE',
        '국가건강검진 안내',
        '국민건강보험공단',
        'PDF',
        'https://www.nhis.or.kr/static/html/wbma/c/wbhaca04500_2025_1.pdf',
        'REFERENCE_ONLY',
        'PENDING',
        NULL,
        NULL,
        NULL,
        TRUE,
        'YEARLY',
        FALSE,
        '사용자 본인 검진결과 조회·발급 경로 확인용. 최신 연도판 확인 필요'
    )
ON CONFLICT (source_code) DO UPDATE SET
    source_name = EXCLUDED.source_name,
    provider_name = EXCLUDED.provider_name,
    source_kind = EXCLUDED.source_kind,
    base_url = EXCLUDED.base_url,
    ingestion_target = EXCLUDED.ingestion_target,
    license_status = EXCLUDED.license_status,
    license_name = EXCLUDED.license_name,
    commercial_use_allowed = EXCLUDED.commercial_use_allowed,
    modification_allowed = EXCLUDED.modification_allowed,
    attribution_required = EXCLUDED.attribution_required,
    refresh_cycle = EXCLUDED.refresh_cycle,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes,
    updated_at = NOW();

UPDATE source_registry
SET
    source_name = '건강검진 실시기준 [별표 4의 별첨] 검사항목별 판정기준',
    source_kind = 'PDF',
    base_url = 'https://law.go.kr/LSW/flDownload.do?bylClsCd=200207&flNm=%5B%EB%B3%84%EC%B2%A8+1%5D+%EA%B2%80%EC%82%AC%ED%95%AD%EB%AA%A9%EB%B3%84+%ED%8C%90%EC%A0%95%EA%B8%B0%EC%A4%80&flSeq=160922929',
    license_status = 'APPROVED',
    license_name = '저작권법 제7조 제2호: 국가·지방자치단체의 고시 등',
    commercial_use_allowed = TRUE,
    modification_allowed = TRUE,
    is_active = TRUE,
    notes = '보건복지부고시 제2026-6호, 2026-01-07 시행. 수치 규칙만 관계형 DB에 구조화',
    updated_at = NOW()
WHERE source_code = 'MOHW_SCREENING_RULE';

UPDATE source_registry
SET
    trust_tier = CASE
        WHEN source_code IN (
            'MFDS_DRUG_GUIDE', 'MFDS_DUR', 'KDCA_HEALTH_INFO', 'MOHW_SCREENING_RULE',
            'NHIS_SCREENING_RESULT_AGG', 'NHIS_SCREENING_ITEM_CODE',
            'NHIS_SCREENING_ITEM_BASE', 'NHIS_SCREENING_CLAIM_CODE', 'NHIS_SCREENING_GUIDE'
        ) THEN 1
        WHEN source_code IN (
            'KDA_DIABETES_GUIDELINE_2025', 'KSN_DKD_GUIDELINE_2023',
            'KSLA_DYSLIPIDEMIA_GUIDELINE_5', 'KASL_HBV_GUIDELINE_2026'
        ) THEN 2
        WHEN source_code = 'INTERNAL_GUIDE' THEN 3
        ELSE 4
    END,
    license_reviewed_at = DATE '2026-07-16';
