#!/usr/bin/env python3
"""Validate the curated corpus and generate deterministic PostgreSQL seed SQL."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import uuid
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CORPUS = ROOT / "vdb/corpus/screening_core_v1.json"
DEFAULT_OUTPUT = ROOT / "database/seeds/030_vdb_core.sql"
UUID_NAMESPACE = uuid.UUID("6965fd21-78bf-4c64-9322-4f1e6768d3d7")
ALLOWED_ROUTES = {
    "SIMPLE_LOOKUP",
    "DRUG_LOOKUP",
    "COMPREHENSIVE_ANALYSIS",
    "PROACTIVE_CARE",
}
ALLOWED_SAFETY = {"LOW", "MODERATE", "HIGH"}
ALLOWED_REVIEW = {"DRAFT", "SOURCE_VERIFIED", "CLINICALLY_APPROVED", "REJECTED"}


def sql_text(value: str | None) -> str:
    if value is None:
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def sql_array(values: list[str]) -> str:
    return "ARRAY[" + ", ".join(sql_text(value) for value in values) + "]::TEXT[]"


def validate(corpus: dict) -> list[str]:
    errors: list[str] = []
    document = corpus.get("document", {})
    chunks = corpus.get("chunks", [])

    for key in ("source_code", "external_document_id", "title", "version_label", "effective_from"):
        if not document.get(key):
            errors.append(f"document.{key} is required")

    if not 20 <= len(chunks) <= 30:
        errors.append(f"MVP corpus must contain 20-30 chunks; found {len(chunks)}")

    seen: set[str] = set()
    required = {
        "canonical_key",
        "heading",
        "domain",
        "section_type",
        "content",
        "keywords",
        "route_scope",
        "safety_level",
        "review_status",
        "evidence",
    }
    for index, chunk in enumerate(chunks):
        prefix = f"chunks[{index}]"
        missing = required - set(chunk)
        if missing:
            errors.append(f"{prefix} missing fields: {sorted(missing)}")
            continue

        key = chunk["canonical_key"]
        if key in seen:
            errors.append(f"duplicate canonical_key: {key}")
        seen.add(key)

        routes = set(chunk["route_scope"])
        if not routes or not routes <= ALLOWED_ROUTES:
            errors.append(f"{prefix}.route_scope contains unsupported values: {sorted(routes)}")
        if chunk["safety_level"] not in ALLOWED_SAFETY:
            errors.append(f"{prefix}.safety_level is invalid")
        if chunk["review_status"] not in ALLOWED_REVIEW:
            errors.append(f"{prefix}.review_status is invalid")
        if len(chunk["content"].strip()) < 80:
            errors.append(f"{prefix}.content is too short for reliable retrieval")
        if not chunk["keywords"]:
            errors.append(f"{prefix}.keywords must not be empty")
        if not chunk["evidence"]:
            errors.append(f"{prefix}.evidence must not be empty")
        for evidence_index, evidence in enumerate(chunk["evidence"]):
            url = evidence.get("url", "")
            if not url.startswith("https://"):
                errors.append(f"{prefix}.evidence[{evidence_index}].url must use https")
            if not evidence.get("label") or not evidence.get("locator"):
                errors.append(f"{prefix}.evidence[{evidence_index}] needs label and locator")

    return errors


def build_sql(corpus: dict) -> str:
    document = corpus["document"]
    chunks = corpus["chunks"]
    document_id = uuid.uuid5(UUID_NAMESPACE, document["external_document_id"])
    summary = document.get("summary", document["title"])

    lines = [
        "-- Generated by scripts/build_vdb_seed.py. Do not edit by hand.",
        "BEGIN;",
        "",
        "INSERT INTO source_document (",
        "    id, source_id, external_document_id, title, document_type, source_url,",
        "    content_format, language_code, version_label, normalized_content,",
        "    ingestion_target, processing_status, published_at, effective_from,",
        "    review_status, clinical_review_status, citation_label, is_retrievable, metadata",
        ") VALUES (",
        f"    {sql_text(str(document_id))}::UUID,",
        f"    (SELECT id FROM source_registry WHERE source_code = {sql_text(document['source_code'])}),",
        f"    {sql_text(document['external_document_id'])},",
        f"    {sql_text(document['title'])},",
        "    'INTERNAL_GUIDE',",
        f"    {sql_text(document.get('source_url'))},",
        "    'MARKDOWN', 'ko',",
        f"    {sql_text(document['version_label'])},",
        f"    {sql_text(summary)},",
        "    'VECTOR', 'CHUNKED',",
        f"    {sql_text(document.get('published_at'))}::TIMESTAMPTZ,",
        f"    {sql_text(document['effective_from'])}::DATE,",
        f"    {sql_text(document['review_status'])},",
        f"    {sql_text(document['clinical_review_status'])},",
        f"    {sql_text(document['citation_label'])},",
        f"    {'TRUE' if document.get('is_retrievable', False) else 'FALSE'},",
        f"    {sql_text(json.dumps(document.get('metadata', {}), ensure_ascii=False, separators=(',', ':')))}::JSONB",
        ")",
        "ON CONFLICT (id) DO UPDATE SET",
        "    title = EXCLUDED.title,",
        "    source_url = EXCLUDED.source_url,",
        "    version_label = EXCLUDED.version_label,",
        "    normalized_content = EXCLUDED.normalized_content,",
        "    processing_status = EXCLUDED.processing_status,",
        "    published_at = EXCLUDED.published_at,",
        "    effective_from = EXCLUDED.effective_from,",
        "    review_status = EXCLUDED.review_status,",
        "    clinical_review_status = EXCLUDED.clinical_review_status,",
        "    citation_label = EXCLUDED.citation_label,",
        "    is_retrievable = EXCLUDED.is_retrievable,",
        "    metadata = EXCLUDED.metadata,",
        "    updated_at = NOW();",
        "",
    ]

    for index, chunk in enumerate(chunks):
        chunk_id = uuid.uuid5(UUID_NAMESPACE, f"{document['external_document_id']}:{chunk['canonical_key']}:v1")
        content_hash = hashlib.sha256(chunk["content"].encode("utf-8")).hexdigest()
        search_text = " ".join([chunk["heading"], chunk["content"], *chunk["keywords"]])
        metadata = {
            "evidence": chunk["evidence"],
            "corpus_version": document["version_label"],
            "authorship": "INTERNAL_SUMMARY",
            "contains_numeric_rule": False,
        }
        lines.extend(
            [
                "INSERT INTO knowledge_chunk (",
                "    id, source_document_id, chunk_index, chunk_version, section_type, heading, content,",
                "    content_hash, canonical_key, domain, route_scope, safety_level, review_status,",
                "    is_retrievable, valid_from, keywords, search_text, metadata",
                ") VALUES (",
                f"    {sql_text(str(chunk_id))}::UUID, {sql_text(str(document_id))}::UUID, {index}, 1,",
                f"    {sql_text(chunk['section_type'])}, {sql_text(chunk['heading'])}, {sql_text(chunk['content'])},",
                f"    {sql_text(content_hash)}, {sql_text(chunk['canonical_key'])}, {sql_text(chunk['domain'])},",
                f"    {sql_array(chunk['route_scope'])}, {sql_text(chunk['safety_level'])}, {sql_text(chunk['review_status'])},",
                f"    {'TRUE' if chunk.get('is_retrievable', True) else 'FALSE'}, {sql_text(document['effective_from'])}::DATE,",
                f"    {sql_array(chunk['keywords'])}, {sql_text(search_text)},",
                f"    {sql_text(json.dumps(metadata, ensure_ascii=False, separators=(',', ':')))}::JSONB",
                ")",
                "ON CONFLICT (id) DO UPDATE SET",
                "    heading = EXCLUDED.heading,",
                "    content = EXCLUDED.content,",
                "    content_hash = EXCLUDED.content_hash,",
                "    canonical_key = EXCLUDED.canonical_key,",
                "    domain = EXCLUDED.domain,",
                "    route_scope = EXCLUDED.route_scope,",
                "    safety_level = EXCLUDED.safety_level,",
                "    review_status = EXCLUDED.review_status,",
                "    is_retrievable = EXCLUDED.is_retrievable,",
                "    valid_from = EXCLUDED.valid_from,",
                "    keywords = EXCLUDED.keywords,",
                "    search_text = EXCLUDED.search_text,",
                "    metadata = EXCLUDED.metadata,",
                "    embedding_model = CASE",
                "        WHEN knowledge_chunk.content_hash = EXCLUDED.content_hash THEN knowledge_chunk.embedding_model",
                "        ELSE NULL",
                "    END,",
                "    embedding = CASE",
                "        WHEN knowledge_chunk.content_hash = EXCLUDED.content_hash THEN knowledge_chunk.embedding",
                "        ELSE NULL",
                "    END,",
                "    embedded_at = CASE",
                "        WHEN knowledge_chunk.content_hash = EXCLUDED.content_hash THEN knowledge_chunk.embedded_at",
                "        ELSE NULL",
                "    END;",
                "",
            ]
        )

    lines.extend(["COMMIT;", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--corpus", type=Path, default=DEFAULT_CORPUS)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    corpus = json.loads(args.corpus.read_text(encoding="utf-8"))
    errors = validate(corpus)
    if errors:
        for error in errors:
            print(f"ERROR: {error}", file=sys.stderr)
        return 1

    generated = build_sql(corpus)
    if args.check:
        if not args.output.exists() or args.output.read_text(encoding="utf-8") != generated:
            print(f"ERROR: {args.output} is not synchronized with {args.corpus}", file=sys.stderr)
            return 1
        print(f"OK: {len(corpus['chunks'])} chunks; generated SQL is synchronized")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated, encoding="utf-8")
    print(f"Wrote {len(corpus['chunks'])} chunks to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

